### ISSUE TITLE
Error when trying to run send-forgot-password-email.php

### ISSUE THREAD

**Issue by tkabir** [devcupboard/elegant-background-job-php-demo#2]
Hi, I'm getting an error with the App\Message\SendForgotPasswordEmail class not found when trying to run `send-forgot-password-email.php`. Although I do not see an issue with the namespace there. What seems to be causing the issue here?

Here's the full error I get:

> I:\Misc. projects\elegant-background-job-php-demo>php bin/send-forgot-password-email.php
PHP Fatal error:  Class 'App\Message\SendForgotPasswordEmail' not found in I:\Misc. projects\elegant-background-job-php-demo\bin\send-forgot-password-email.php on line 20

> Fatal error: Class 'App\Message\SendForgotPasswordEmail' not found in I:\Misc. projects\elegant-background-job-php-demo\bin\send-forgot-password-email.php on line 20

**Comment by ojhaujjwal** [comment]
Thanks for the issue. Fixed in fd42f8552b0781c5bd9cba581626fe314fd2acd1

**Comment by tkabir** [comment]
> Thanks for the issue. Fixed in [fd42f85](https://github.com/devcupboard/elegant-background-job-php-demo/commit/fd42f8552b0781c5bd9cba581626fe314fd2acd1)

Great! Much thanks for the quick fix. All is good now :)
